* File name: fridays_for_future_change_addresses_of_strikes_ordnungsämter_20201106_review.do
* Author: LLeutner
* Date: 11/06/20
* Description: This program replaces information about locations and addresses of the strikes reported by the Ordnungsämter if they do not provide street
* information. With help of google maps the names of streets of the respective places are searched for.

* Inputs: maps.google.com
***************************************************************************/
replace location = "Allerheiligenstraße" if municipality == "achern" & location == "kirchplatz"
replace location = "Obernstraße" if municipality == "achim" & location == "bibiotheksplatz"
replace location = "universitätsstrasse" if municipality == "augsburg" & location == "haltestelle universität"
replace location = "willy-brandt-platz" if municipality == "augsburg" & location == "citygalerie"
replace location = "marktplatz" if municipality == "bad camberg" & location == "altstadt"
replace location = "kirchplatz" if municipality == "bad essen" & location == "kirchplatz "
replace address = "lindenstrasse" if municipality == "bad essen" & address == "rathausplatz"
replace location = "hauptstrasse" if municipality == "bad waldsee" & location == "fußgaengerzone rathausplatz"
replace location = "hochstatt" if municipality == "bad waldsee" & location == "fußgaengerzone hochstatt"
replace location = "bahnhofstraße" if municipality == "bassum" & location == "bahnhof"
replace address = "lindenstraße" if address == "lindenstraße2"
replace location = "Bürgermeister-Müller-Straße" if municipality == "brake" & location == "platz vor dem behördenzentrum"
replace location = "Willy-Brandt-Platz" if municipality == "braunschweig" & location == "bahnhofsplatz"
replace location = "universitätsallee" if municipality == "bremen" & location == "siemens" & address == "bahnhofsplatz"
replace location = "am markt" if municipality == "bremen" & location == "bahnhofsvorplatz" & address == "marktplatz"
replace location = "am markt" if municipality == "bremen" & location == "marktplatz"
replace location = "bahnhofsplatz" if municipality == "bremen" & location == "bahnhofsvorplatz"
replace location = "Bürgermeister-Smidt-Straße" if municipality == "bremerhaven" & location == "bürgerm.-smidt-gedaechtniskirche"
replace location = "am seedeich" if municipality == "bremerhaven" & location == "weserdeich"
replace location = "markt" if municipality == "coburg" & location == "marktplatz"
replace location = "am bahnhof" if municipality == "cuxhaven" & location == "bahnhofsplatz" & address == "bahnhofsplatz"
replace location  = "willmsstraße" if municipality == "delmenhorst" & location == "gymnasium an der willmstraße"
replace location  = "thouarsstraße" if municipality == "diepholz" & location == "thouarstraße"
replace address = "erdinger straße" if municipality == "dorfen" & address == "erdinger straße/am mitterfeld"
replace location = "spitalstraße" if municipality == "ellwangen" & location == "fußgaengerzone"
replace location = "rathausstraße" if municipality == "elz" & location == "rathausplatz"
replace location = "rathausplatz" if municipality == "emden" & location == "innenstadt"
replace location = "am zwinger" if municipality == "feuchtwangen" & location == "zwinger" & address == "stadtpark"
// municipality == "frankfurt am main", street "Zeil" -> located in two electoral districts (streetname changed accordingly)
replace location = "guenthersburgallee" if municipality == "frankfurt am main" & location == "guenthersburgweg"
replace location = "wetteraustraße" if municipality == "frankfurt am main" & location == "guenthersburgpark"
replace address = "oppenheimer strasse 17" if municipality == "frankfurt am main"  & address == "oppenheimerstrasse 17"
replace address = "hugo-eckener ring" if municipality == "frankfurt am main" & address == "hugo-eckener ring parkplatz b36"
replace location = "hugo-eckener ring" if municipality == "frankfurt am main" & location == "abflughalle a, terminal 1"
replace location = "eckhardtstraße" if municipality == "frankfurt am main" & location == "weseler werft"
replace location = "schlinkenweg" if municipality == "frankfurt am main" & location == "schlinkenweg/kleingartenweg"
replace location = "bockenheimer landstraße" if municipality == "frankfurt am main" & location == "bockenheimer warte"
replace location = "konrad-adenauer-strasse" if municipality == "frankfurt am main" & location == "konstablerwache"
replace location = "gisèle-freud-platz" if municipality == "frankfurt am main" & location == "gisele freud platz"
replace location = "stiftstraße" if municipality == "frankfurt am main" & address == "brockhausbrunnen"
replace location = "an der hauptwache" if municipality == "frankfurt am main" & location == "hauptwache"
replace location = "am markt" if municipality == "friedland" & location == "marktplatz"
replace location = "kasseler straße" if municipality == "fritzlar" & location == "platz vor der stadthalle"
replace location = "mühlenstraße" if municipality == "ganderkesee" & location == "rathaus"
replace location = "frankfurter straße" if municipality == "gross-gerau" & location == "innenstadt"
replace address = "karmarschstraße" if municipality == "hannover" & address == "platz der goettinger sieben"
replace address = "ständehausstraße" if municipality == "hannover" & address == "kroepcke"
replace address = "jägerstraße" if municipality == "hannover" & address == "georgengarten"
replace location = "allee" if municipality == "heilbronn" & location == "innenstadt"
replace address = "wassertorstraße 1" if municipality == "isny" & location == "rathaus"
replace location = "wassertorstraße" if municipality == "isny" & location == "innenstadt"
replace location = "Karl-Wilhelm-Heck-Straße" if municipality == "isny" & location == "skaterpark"
replace location = "Karl-Wilhelm-Heck-Straße" if municipality == "isny" & location == "skaterplatz"
replace address = "Wassertorstraße" if municipality == "isny" & address == "wassertorstraße 1"
replace location = "tiergartenstraße" if municipality == "jade" & location == "innenstadt"
replace location = "schlossbezirk" if municipality == "karlsruhe" & location == "schlossvorplatz"
replace location = "durlacher allee" if municipality == "karlsruhe" & location == "otto-dullenkopf-park"
replace location = "ritterstraße" if municipality == "karlsruhe" & location == "friedrichsplatz"
replace location = "hermann-levi-platz" if municipality == "karlsruhe" & location == "staatstheater"
replace location = "hauptstrasse" if municipality == "koenigstein im taunus" & location == "innenstadt"
replace location = "hafenstrasse" if municipality == "konstanz" & location == "konzilvorplatz"
replace location = "untere laube" if municipality == "konstanz" & location == "gehweg untere laube"
replace location = "mainaustraße" if municipality == "konstanz" & location == "krankenhauspark"
replace location = "kanzleistraße" if municipality == "konstanz" & location == "rathaus"
replace location = "sankt-stephans-platz" if municipality == "konstanz" & location == "st stephans platz"
replace location = "am berndorfer tor" if municipality == "korbach" & location == "berndorfer tor platz"
replace location = "Roßplatz" if municipality == "leipzig" & location == "Willhelm-Leuschner-Platz"
replace location = "bahnhofsring" if municipality == "leer" & location == "vorplatz des zollhauses "
replace location = "blinke" if municipality == "leer" & location == "parkplatz an der BBS I leer"
replace location = "weststraße" if municipality == "melle" & location == "innenstadt"
replace location = "markt" if municipality == "melle" & location == "wochenmarkt"
replace location = "markt" if municipality == "melle" & location == "starcke carree"
replace location = "bahnhofstraße" if municipality == "moeckmuehl" & location == "unterer marktplatz"
replace location = "hauptstrasse" if municipality == "neckargemuend" & location == "haupstraße"
replace location = "dekan-martin-straße" if municipality == "neuenburg" & location == "rathausplatz"
replace address = "am kurplatz 1" if municipality == "norderney" & address == "kurplatz 1"
replace location = "messezentrum" if municipality == "nuernberg" & location == "messegelaende"
replace location = "markt" if municipality == "osnabrueck" & location == "marktplatz"
replace location = "am grünen markt" if municipality == "puchheim" & location == "gruener markt"
replace location = "bahnhof puchheim" if municipality == "puchheim" & location == "bahnhof"
replace location = "bahnhofsallee" if municipality == "ratzeburg" & location == "lauenburgische gelehrtenschule"
replace location = "unter den linden" if municipality == "ratzeburg" & location == "rathausplatz"
replace location = "universitätsstrasse" if municipality == "regensburg" & location == "uni"
replace address = "friedrichstraße 28" if municipality == "schriesheim" & address == "freidrichstraße 28"
replace location = "Marktplatz" if municipality == "stuttgart" & location == "Rathaus"
replace location = "lange straße" if municipality == "sulingen" & location == "neuer markt"
replace location = "münchner ring" if municipality == "unterschleißheim" & location == "radlhof gymnasium"
replace location = "kurt-zimmermann-straße" if municipality == "uslar" & location == "karl-zimmermann-straße"
replace location = "marktstraße" if municipality == "wiesloch" & location == "markstraße 13"
replace location = "am markt" if municipality == "wildeshausen" & location == "marktplatz"
replace location = "bahnhofstraße" if municipality == "wildeshausen" & location == "bahnhof"
replace location = "Friedenstraße" if municipality == "wilhelmshaven" & location == "jadestadion"
replace location = "am amtshof" if municipality == "winsen (aller)" & location == "rathausplatz"
replace location = "am Exerzierpl." if municipality == "wuerzburg" & location == "exerzierplatz"